version: '3'
services:
  openresty:
    build:
      context: ./openresty/
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /www:/www
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8888:8888
      - 22122:22122
      - 23000:23000
      - 8080:8080
    container_name: openresty
networks:
  internal:
